include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Errores comunes
    avoid_print: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    prefer_relative_imports: true

    # Estilo
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true

    # Buenas prácticas
    always_declare_return_types: true
    always_use_package_imports: false
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true

    # Null safety
    prefer_null_aware_operators: true
    avoid_null_checks_in_equality_operators: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "build/**"
  errors:
    invalid_annotation_target: ignore
